// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2uakdS0DimyJDMgY1yViPpGBL6yuu1gA',
    appId: '1:722820386681:web:9ec9efbed43b3e70ae29a8',
    messagingSenderId: '722820386681',
    projectId: 'insta-auth-163a5',
    authDomain: 'insta-auth-163a5.firebaseapp.com',
    storageBucket: 'insta-auth-163a5.appspot.com',
    measurementId: 'G-6530J1290C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4iPoZPSHwkoAus6PymLWnG-g-bDHfzNU',
    appId: '1:722820386681:android:ba417440c1ebce7bae29a8',
    messagingSenderId: '722820386681',
    projectId: 'insta-auth-163a5',
    storageBucket: 'insta-auth-163a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDyI3--Mvx2g6XOTG6Yn3xmHOYreuJu6A',
    appId: '1:722820386681:ios:115d1b5c5603c62cae29a8',
    messagingSenderId: '722820386681',
    projectId: 'insta-auth-163a5',
    storageBucket: 'insta-auth-163a5.appspot.com',
    iosBundleId: 'com.example.instagramLoginUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDyI3--Mvx2g6XOTG6Yn3xmHOYreuJu6A',
    appId: '1:722820386681:ios:115d1b5c5603c62cae29a8',
    messagingSenderId: '722820386681',
    projectId: 'insta-auth-163a5',
    storageBucket: 'insta-auth-163a5.appspot.com',
    iosBundleId: 'com.example.instagramLoginUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2uakdS0DimyJDMgY1yViPpGBL6yuu1gA',
    appId: '1:722820386681:web:605d8ac4411df6fbae29a8',
    messagingSenderId: '722820386681',
    projectId: 'insta-auth-163a5',
    authDomain: 'insta-auth-163a5.firebaseapp.com',
    storageBucket: 'insta-auth-163a5.appspot.com',
    measurementId: 'G-7C2ZE5BD3S',
  );
}
